### ISSUE TITLE
Package ‘EcolUtils’ is not available (for R version 4.0.0)

### ISSUE THREAD

**Issue by costavale** [GuillemSalazar/EcolUtils#3]
Hi,
are you planning to update the package for R 4.0 ?

Thanks

**Comment by SteffenMoritz** [comment]
I think in this case that just means, that it is not on CRAN. So install.packages() does not work. (because it searches on CRAN for the package). Just type devtools::install_github("GuillemSalazar/EcolUtils") to get the package.
.
